import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/components/query-provider";
import { YamadaUIScript } from "@/components/yamada-ui-script";
import { YamadaUIProvider } from "@/components/yamada-ui-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    /**
     * ハイドレーションエラーへの一時的な対処。
     * html、bodyタグに「suppressHydrationWarning」を追加する。
     * @see https://github.com/yamada-ui/yamada-ui/issues/3363
     */
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <YamadaUIScript />
        <YamadaUIProvider>
          <QueryProvider>{children}</QueryProvider>
        </YamadaUIProvider>
      </body>
    </html>
  );
}
